### PR TITLE
Allow modifying cookies, just like modifying headers

### PR DESCRIPTION
**Pull request by recolic**
I added code to add/modify/delete a single cookie element. I did some simple tests on them on Firefox, and it seems to be working. 
It solves issue #31 
Just let me know if there's any design issues.

### CODE REVIEW

**Comment by recolic** [comment]
Hi. I have finished the new code about response modify, however, it's not working in my tests. 
What's more, the existing `response header add` is also not working in my test. 

I'm using chromium on Linux. Could you help me double-confirm if the existing code is working? This is my testing config: 
```
{"format_version":"1.2","target_page":"https://mail.recolic.net/mail/*","headers":[{"url_contains":"","action":"cookie_add_or_modify","header_name":"roundcube_sessauth","header_value":"shit","comment":"test","apply_on":"res","status":"on"},{"url_contains":"","action":"add","header_name":"ggfuck","header_value":"gggg","comment":"","apply_on":"res","status":"on"},{"url_contains":"","action":"cookie_add_or_modify","header_name":"youarebad","header_value":"bad","comment":"ss","apply_on":"req","status":"on"}],"debug_mode":false,"show_comments":true,"use_url_contains":false}
```

**Comment by didierfred** [comment]
In your code , you are using e.requestHeaders instead of e.responseHeaders ?

```
      else if (to_modify.action === "cookie_add_or_modify") {
        let header_cookie = e.requestHeaders.find(header => 
            header.name.toLowerCase() === "set-cookie" && 
```

When executing the plugin on my chrome : 

image

**Comment by recolic** [comment]
Oh. I fixed this mistake just now, but it's not the root cause of issue. 

In my test, the existing `response header add` is also not working. There should be a `ggfuck: gggg` header in response, but there's none. 

image

**Comment by didierfred** [comment]
it works on my computer , i m using chrome Version 89.0.4389.114

image

image

**Comment by recolic** [comment]
Great. Then there should be no problem in our code. 

maybe something went wrong in my environment, which is not related to this PR.

**Comment by didierfred** [comment]
when you try to modify the response header  without your modification in the plugin does it works ?

**Comment by recolic** [comment]
||modify request header|modify response header|
|---|---|---|
|from ChromeWebStore|Working|Not working|
|git repo before my PR|Working|Not working|
|git repo after my PR|Working|Not working|

I'm using Chromium Version 95.0.4638.69 (Official Build) Arch Linux (64-bit)

**Comment by didierfred** [comment]
i updated my chrome version , which is now Version 95.0.4638.69 (Build officiel) (64 bits)

I do not see anymore the header in the log , it seems that we have the same problem as firefox : see issue  https://github.com/didierfred/SimpleModifyHeaders/issues/19

But the response header is still modify , if i set a header content-type to  text/plain , the text of the html page show up which means the navigator get the header . And if i change cookie , i see it in the application storage

image

image

**Comment by recolic** [comment]
Then I believe the new code is good. This issue is not related to this PR.

**Pull request merged**
